# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
test:
  adapter: postgresql
  database: production
  username: username
  password: password
  host: localhost

development:
  adapter: postgresql
  database: production
  username: username
  password: password
  host: localhost

production:
  adapter: postgresql
  database: production
  username: username
  password: password
  host: localhost

